final Map<String, String> enUS = {
  'title': 'AU Mining',
  'subtitleOnboarding': 'Mine digital gold, build your fortune',
  'login': 'Login',
  'signup': 'Sign Up',
  'emailLabel': 'Email',
  'emailHint': 'Enter your email',
  'passwordLabel': 'Password',
  'passwordHint': 'Enter password',
  'loginWithEmail': 'Login with email',
  'signUpWithEmail': 'Sign Up with email',
  'consent': 'By continuing, you agree to our Terms & Privacy Policy',
  'orContinueWith': 'Or continue with',
  'google': 'Google',
  'phone': 'Phone',
  'name': 'Name',
  'nameHint':" Enter your name",
  'phoneOptional': "Phone (Optional)",
  'phoneOptionalHint': "Enter your phone number",
  'referral': "Referral code (Optional)",
  'referralHint': "Enter referral code",
  'mineGoldBuildFortune':'Mine digital gold, build your fortune',
  'welcome':'Welcome, ',
};
