// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAILo6kz2VVYZOAfnqwHWnHTWhladAuAhU',
    appId: '1:1080476079769:web:52a1b6cfe697d514790a08',
    messagingSenderId: '1080476079769',
    projectId: 'audigi-pay',
    authDomain: 'audigi-pay.firebaseapp.com',
    storageBucket: 'audigi-pay.firebasestorage.app',
    measurementId: 'G-N12C5M78YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiGxctN6kcMtmSoAkE9wd2mwf-y0OkGyo',
    appId: '1:1080476079769:android:f9e24ebf1d87bf74790a08',
    messagingSenderId: '1080476079769',
    projectId: 'audigi-pay',
    storageBucket: 'audigi-pay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUHFGSK2VOc2mvSQKuRWf5sOoEHd48Rmc',
    appId: '1:1080476079769:ios:d19ad609130e7327790a08',
    messagingSenderId: '1080476079769',
    projectId: 'audigi-pay',
    storageBucket: 'audigi-pay.firebasestorage.app',
    iosBundleId: 'com.example.miningApplication',
  );
}
